# Configuration for chaos experiment data generator

[general]
output_dir = "output"
num_samples = 150

[metrics]

    [metrics.instances]
    value = 4
    step_size=1
    noise = "exponential"
    noise_args = {"scale" = 0.48, "smoothing_window" = 30}

    [metrics.cpu_usage]
    value = 60
    step_size=0.1
    noise = "gaussian"
    noise_args = {"loc" = 0, "scale" = 1, "smoothing_window" = 10}

    [metrics.memory_usage_mb]
    value = 2000
    step_size=0.01
    noise = "logistic"
    noise_args = {"loc" = 0, "scale" = 10, "smoothing_window" = 60}

    [metrics.response_time_s]
    value = 0.006
    step_size=0.00001
    noise = "exponential"
    noise_args = {"scale" = 0.0001, "smoothing_window" = 1}

[anomalies]

    [anomalies.instances]
    at = 40
    magnitude_factor = 2
    pattern = "step"
    recovery_time = 20

    [anomalies.cpu_usage]
    at = 35
    magnitude_factor = 1.3
    pattern = "exponential"
    recovery_time = 30

    [anomalies.memory_usage_mb]
    at = 10
    magnitude_factor = 0.4
    pattern = "oscillating"
    recovery_time = 40
    pattern_args = {"frequency" = 0.3}

    [anomalies.response_time_s]
    at = 12
    magnitude_factor = 2
    pattern = "oscillating"
    recovery_time = 50
    pattern_args = {"frequency" = 0.25}
